### ISSUE TITLE
A version conflict in license checker should not prevent app from working

### ISSUE THREAD

**Issue by Artur-** [vaadin/license-checker#60]
If you do
```
npm i @vaadin/vaadin-board@2.1.0-alpha1
npm i @vaadin/vaadin-charts@6.2.0-alpha2
```

you end up with
```
$ npm ls
├─┬ @vaadin/vaadin-board@2.1.0-alpha1
│ └─┬ @vaadin/vaadin-license-checker@2.1.0-beta1
└─┬ @vaadin/vaadin-charts@6.2.0-alpha2
  ├─┬ @vaadin/vaadin-license-checker@2.1.0-alpha2
```

Both of the versions are loaded in the browser, both try to define a custom element and
```
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at eval (eval at uncommentAndRun (http://localhost:8081/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js:53:18), <anonymous>:106:18)
    at eval (eval at uncommentAndRun (http://localhost:8081/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js:53:18), <anonymous>:378:4)
    at uncommentAndRun (http://localhost:8081/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js:60:10)
    at runIfDevelopmentMode (http://localhost:8081/node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js:81:12)
    at http://localhost:8081/node_modules/@vaadin/vaadin-charts/node_modules/@vaadin/vaadin-license-checker/vaadin-license-checker.js:391:3
```

This should never ever happen

**Comment by alvarezguille** [comment]
Will be fixed in each component depending on license checker, all were updated to use `vaadin/license-checker#^2.1.0-beta1` although only vaadin-charts that was depending on `vaadin/license-checker#2.1.0-alpha2` (without range) 

PRs:

- https://github.com/vaadin/vaadin-board/pull/114
- https://github.com/vaadin/vaadin-charts/pull/427
- https://github.com/vaadin/vaadin-cookie-consent/pull/55
- https://github.com/vaadin/vaadin-confirm-dialog/pull/64
- https://github.com/vaadin/vaadin-app-layout/pull/46
- https://github.com/vaadin/vaadin-crud/pull/112
- https://github.com/vaadin/vaadin-rich-text-editor/pull/54
